import uuid
import json
import os

class Note:
    def __init__(self, title, content, color="white", id=None):
        self.id = id if id else uuid.uuid4().hex
        self.title = title
        self.content = content
        self.color = color

class NotesManager:
    def __init__(self, filename="notes.json"):
        self.notes = []
        self.filename = filename
        self.load_notes_from_file()

    def create_note(self, title, content, color="white"):
        # id is generated by Note constructor if not provided
        note = Note(title, content, color)
        self.notes.append(note)
        self.save_notes_to_file() # Save after creating a note
        return note

    def edit_note(self, note_id, title=None, content=None, color=None):
        note_found = False
        for note in self.notes:
            if str(note.id) == note_id: # Ensure comparison is with string form of ID
                if title is not None:
                    note.title = title
                note_found = True
                if content is not None:
                    note.content = content
                if color is not None:
                    note.color = color
                if note_found:
                    self.save_notes_to_file() # Save after editing a note
                return True # Return True if note was found and potentially updated
        return False # Return False if note_id was not found

    def delete_note(self, note_id):
        original_len = len(self.notes)
        self.notes = [note for note in self.notes if str(note.id) != note_id]
        if len(self.notes) < original_len:
            self.save_notes_to_file() # Save after deleting a note
            return True
        return False

    def save_notes_to_file(self):
        notes_as_dicts = []
        for note in self.notes:
            notes_as_dicts.append({
                "id": str(note.id), # Ensure ID is string
                "title": note.title,
                "content": note.content,
                "color": note.color
            })
        try:
            with open(self.filename, 'w') as f:
                json.dump(notes_as_dicts, f, indent=4)
        except IOError:
            print(f"Error: Could not save notes to {self.filename}")

    def load_notes_from_file(self):
        if not os.path.exists(self.filename):
            self.notes = [] # Ensure notes is empty if file doesn't exist
            return

        try:
            with open(self.filename, 'r') as f:
                notes_data = json.load(f)
                self.notes = [] # Clear existing notes before loading
                for note_dict in notes_data:
                    # Pass id directly to Note constructor
                    note = Note(
                        id=note_dict['id'],
                        title=note_dict['title'],
                        content=note_dict['content'],
                        color=note_dict['color']
                    )
                    self.notes.append(note)
        except (IOError, json.JSONDecodeError):
            print(f"Error: Could not load notes from {self.filename} or file contains invalid JSON.")
            self.notes = [] # Ensure notes is empty on error

    def search_notes(self, query):
        matching_notes = []
        query_lower = query.lower()
        for note in self.notes:
            if query_lower in note.title.lower() or \
               query_lower in note.content.lower():
                matching_notes.append(note)
        return matching_notes

if __name__ == '__main__':
    # Example Usage (Optional - for testing purposes)
    manager = NotesManager("my_notes.json")

    # Create a few notes
    if not manager.notes: # Check if notes are already loaded
        print("Creating new notes...")
        note1 = manager.create_note("First Note", "This is the first note.", "blue")
        note2 = manager.create_note("Second Note", "This is a test of the JSON storage.", "green")
        print(f"Note 1 ID: {note1.id}")
        print(f"Note 2 ID: {note2.id}")
    else:
        print(f"Loaded {len(manager.notes)} notes from {manager.filename}")
        for n in manager.notes:
            print(f"Loaded Note: ID - {n.id}, Title - {n.title}")

    # Search for notes
    print("\nSearching for 'first':")
    results = manager.search_notes("first")
    for note in results:
        print(f"Found: {note.title} - {note.content}")

    # Edit a note (assuming note1 was created and we know its id)
    if manager.notes:
        first_note_id = manager.notes[0].id
        print(f"\nEditing note with ID: {first_note_id}")
        if manager.edit_note(first_note_id, title="Updated First Note", content="Content has been updated!"):
            print("Note edited successfully.")
            print(f"Updated Title: {manager.notes[0].title}")
        else:
            print("Failed to edit note.")

    # Delete a note (assuming the second note exists)
    if len(manager.notes) > 1:
        second_note_id = manager.notes[1].id
        print(f"\nDeleting note with ID: {second_note_id}")
        if manager.delete_note(second_note_id):
            print("Note deleted successfully.")
        else:
            print("Failed to delete note.")
    
    print(f"\nFinal notes count: {len(manager.notes)}")
    # To clean up the created file after testing:
    # if os.path.exists("my_notes.json"):
    # os.remove("my_notes.json")
    # print("Cleaned up my_notes.json")
